# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/anura/Downloads/project_bram_new/project_bram/project_bram/project_bram.srcs/sources_1/ip/bram_2/bram_2.xci
# IP: The module: 'bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anura/Downloads/project_bram_new/project_bram/project_bram/project_bram.srcs/sources_1/ip/bram_2/bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/anura/Downloads/project_bram_new/project_bram/project_bram/project_bram.srcs/sources_1/ip/bram_2/bram_2.xci
# IP: The module: 'bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anura/Downloads/project_bram_new/project_bram/project_bram/project_bram.srcs/sources_1/ip/bram_2/bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
